"""empty message

Revision ID: ce22d687fe0f
Revises: 
Create Date: 2018-07-09 02:48:55.099123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce22d687fe0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_currency_currency'), 'base_currency', ['currency'], unique=False)
    op.create_index(op.f('ix_base_currency_date'), 'base_currency', ['date'], unique=False)
    op.create_table('currency_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('base_currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_id'], ['base_currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'base_currency_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rate')
    op.drop_index(op.f('ix_base_currency_date'), table_name='base_currency')
    op.drop_index(op.f('ix_base_currency_currency'), table_name='base_currency')
    op.drop_table('base_currency')
    # ### end Alembic commands ###
